server:
  port: 8080
  servlet:
    contextPath: /

spring:
  application: zipkin-server1

  zipkin:
    baseUrl: http://localhost:9411/

  sleuth:
    enabled: true
    sampler:
      probability: 1.0

  sample:
    zipkin:
      # When enabled=false, traces log to the console. Comment to send to zipkin
      enabled: true