server:
  port: 8080
  contextPath: /

spring:
  h2:
    console:
      enabled: true
  jpa:
      hibernate:
        ddl-auto: create-drop
        show-sql: true

logging:
  level:
    org.hibernate.SQL: debug

